## Python Pandas

Importing library

In [1]:
import pandas as pd

In [2]:
data = [100,102,104]

series = pd.Series(data)

print(series)

0    100
1    102
2    104
dtype: int64

In [3]:
data = ['A','B','C']

series = pd.Series(data)

print(series)

0    A
1    B
2    C
dtype: str

### Series

In [4]:
data = [100,102,104]

series = pd.Series(data, index=["a","b","c"])

print(series)

a    100
b    102
c    104
dtype: int64

### loc - location

In [5]:
print(series.loc["a"])

100

In [6]:
series.loc["c"] = 200

series

a    100
b    102
c    200
dtype: int64

### iloc - index location

In [7]:
print(series.iloc[1])

102

### Conditionals

In [8]:
print(series[series >= 200])

c    200
dtype: int64

In [9]:
print(series[series < 200])

a    100
b    102
dtype: int64

In [10]:
calories = {"Day 1": 1750, "Day 2": 2100, "Day 3": 1700}

series = pd.Series(calories)

print(series)

Day 1    1750
Day 2    2100
Day 3    1700
dtype: int64

In [12]:
series.loc["Day 3"] += 500

series.loc["Day 3"]

np.int64(2700)

### DataFrame
Tabular form of data

In [14]:
data = {"Name": ["Spongebob","Patrick","Squidward"],
        "Age": [30,35,50]}

df = pd.DataFrame(data, index=["Employee 1", "Employee 2", "Employee 3"])

print(df)

                 Name  Age
Employee 1  Spongebob   30
Employee 2    Patrick   35
Employee 3  Squidward   50

In [15]:
df.loc["Employee 1"]

Name    Spongebob
Age            30
Name: Employee 1, dtype: object

In [16]:
df.iloc[1]

Name    Patrick
Age          35
Name: Employee 2, dtype: object

### Add a new column

In [18]:
df["Job"] = ["Cook","N/A","Cashier"]

df

                 Name  Age      Job
Employee 1  Spongebob   30     Cook
Employee 2    Patrick   35      N/A
Employee 3  Squidward   50  Cashier

In [ ]:
new_row = pd.DataFrame([{"Name": "Sandy", "Age": 28, "Job": "Engineer"}],['Employee 4'])

pd.concat([df, new_row])

                 Name  Age       Job
Employee 1  Spongebob   30      Cook
Employee 2    Patrick   35       N/A
Employee 3  Squidward   50   Cashier
Employee 4      Sandy   28  Engineer

### Importing files

In [ ]:
df = pd.read_csv("sample-employees.csv")

print(df.to_string())

                name                         email   department                      role  salary  start_date         office
0        Marcus Chen       marcus.chen@example.com  Engineering  Senior Software Engineer  155000  2019-03-15  San Francisco
1       Priya Sharma      priya.sharma@example.com  Engineering            Staff Engineer  178000  2019-06-01  San Francisco
2          David Kim         david.kim@example.com  Engineering         Software Engineer  125000  2021-01-10       New York
3      Rachel Torres     rachel.torres@example.com  Engineering       Engineering Manager  168000  2020-02-20  San Francisco
4       James Okafor      james.okafor@example.com  Engineering          Junior Developer   92000  2024-06-15         Austin
5          Lena Vogt         lena.vogt@example.com  Engineering           DevOps Engineer  140000  2022-04-01       New York
6         Amir Patel        amir.patel@example.com  Engineering          Backend Engineer  132000  2023-01-09         London
7     Sofia Lindberg    sofia.lindberg@example.com       Design             Lead Designer  145000  2019-09-12       New York
8      Carlos Rivera     carlos.rivera@example.com       Design               UX Designer  112000  2021-07-20  San Francisco
9      Hannah Becker     hannah.becker@example.com       Design               UI Designer  105000  2022-11-01         London
10       Yuki Tanaka       yuki.tanaka@example.com       Design          Product Designer  118000  2023-03-14  San Francisco
11     Olivia Martin     olivia.martin@example.com    Marketing           VP of Marketing  165000  2019-04-22       New York
12      Ethan Brooks      ethan.brooks@example.com    Marketing        Content Strategist   95000  2021-10-05         Austin
13     Nina Kowalski     nina.kowalski@example.com    Marketing            SEO Specialist   88000  2022-08-15       New York
14      Daniel Ochoa      daniel.ochoa@example.com    Marketing         Marketing Analyst   91000  2023-05-20         Austin
15     Samira Hassan     samira.hassan@example.com    Marketing      Social Media Manager   82000  2024-01-08         London
16  Tyler Washington  tyler.washington@example.com        Sales            Sales Director  158000  2019-11-30       New York
17     Jessica Huang     jessica.huang@example.com        Sales         Account Executive  110000  2020-06-14  San Francisco
18      Ryan O'Brien       ryan.obrien@example.com        Sales         Account Executive  105000  2021-03-22         London
19  Fatima Al-Rashid   fatima.alrashid@example.com        Sales     Sales Development Rep   72000  2023-09-01         Austin
20      Kevin Dupont      kevin.dupont@example.com        Sales        Solutions Engineer  135000  2022-01-17  San Francisco
21     Megan Stewart     megan.stewart@example.com        Sales           Account Manager   98000  2024-03-11       New York
22        Laura Chen        laura.chen@example.com           HR               HR Director  148000  2019-08-05       New York
23    Brian Nakamura    brian.nakamura@example.com           HR       HR Business Partner  105000  2020-12-01  San Francisco
24      Chloe Dubois      chloe.dubois@example.com           HR                 Recruiter   78000  2022-05-23         London
25    Angela Moretti    angela.moretti@example.com           HR         People Operations   85000  2023-07-10         Austin
26   Isaac Fernandez   isaac.fernandez@example.com  Engineering         Frontend Engineer  128000  2022-09-19       New York
27    Sarah Mitchell    sarah.mitchell@example.com       Design       Design Systems Lead  138000  2020-04-06  San Francisco
28        Omar Farah        omar.farah@example.com  Engineering               QA Engineer   95000  2024-02-12         London
29      Natalie Park      natalie.park@example.com    Marketing            Growth Manager  108000  2021-11-28  San Francisco

In [9]:
df = pd.read_json("sample-employees.json")

print(df.to_string())

                name                         email   department                      role  salary  start_date         office
0        Marcus Chen       marcus.chen@example.com  Engineering  Senior Software Engineer  155000  2019-03-15  San Francisco
1       Priya Sharma      priya.sharma@example.com  Engineering            Staff Engineer  178000  2019-06-01  San Francisco
2          David Kim         david.kim@example.com  Engineering         Software Engineer  125000  2021-01-10       New York
3      Rachel Torres     rachel.torres@example.com  Engineering       Engineering Manager  168000  2020-02-20  San Francisco
4       James Okafor      james.okafor@example.com  Engineering          Junior Developer   92000  2024-06-15         Austin
5          Lena Vogt         lena.vogt@example.com  Engineering           DevOps Engineer  140000  2022-04-01       New York
6         Amir Patel        amir.patel@example.com  Engineering          Backend Engineer  132000  2023-01-09         London
7     Sofia Lindberg    sofia.lindberg@example.com       Design             Lead Designer  145000  2019-09-12       New York
8      Carlos Rivera     carlos.rivera@example.com       Design               UX Designer  112000  2021-07-20  San Francisco
9      Hannah Becker     hannah.becker@example.com       Design               UI Designer  105000  2022-11-01         London
10       Yuki Tanaka       yuki.tanaka@example.com       Design          Product Designer  118000  2023-03-14  San Francisco
11     Olivia Martin     olivia.martin@example.com    Marketing           VP of Marketing  165000  2019-04-22       New York
12      Ethan Brooks      ethan.brooks@example.com    Marketing        Content Strategist   95000  2021-10-05         Austin
13     Nina Kowalski     nina.kowalski@example.com    Marketing            SEO Specialist   88000  2022-08-15       New York
14      Daniel Ochoa      daniel.ochoa@example.com    Marketing         Marketing Analyst   91000  2023-05-20         Austin
15     Samira Hassan     samira.hassan@example.com    Marketing      Social Media Manager   82000  2024-01-08         London
16  Tyler Washington  tyler.washington@example.com        Sales            Sales Director  158000  2019-11-30       New York
17     Jessica Huang     jessica.huang@example.com        Sales         Account Executive  110000  2020-06-14  San Francisco
18      Ryan O'Brien       ryan.obrien@example.com        Sales         Account Executive  105000  2021-03-22         London
19  Fatima Al-Rashid   fatima.alrashid@example.com        Sales     Sales Development Rep   72000  2023-09-01         Austin
20      Kevin Dupont      kevin.dupont@example.com        Sales        Solutions Engineer  135000  2022-01-17  San Francisco
21     Megan Stewart     megan.stewart@example.com        Sales           Account Manager   98000  2024-03-11       New York
22        Laura Chen        laura.chen@example.com           HR               HR Director  148000  2019-08-05       New York
23    Brian Nakamura    brian.nakamura@example.com           HR       HR Business Partner  105000  2020-12-01  San Francisco
24      Chloe Dubois      chloe.dubois@example.com           HR                 Recruiter   78000  2022-05-23         London
25    Angela Moretti    angela.moretti@example.com           HR         People Operations   85000  2023-07-10         Austin
26   Isaac Fernandez   isaac.fernandez@example.com  Engineering         Frontend Engineer  128000  2022-09-19       New York
27    Sarah Mitchell    sarah.mitchell@example.com       Design       Design Systems Lead  138000  2020-04-06  San Francisco
28        Omar Farah        omar.farah@example.com  Engineering               QA Engineer   95000  2024-02-12         London
29      Natalie Park      natalie.park@example.com    Marketing            Growth Manager  108000  2021-11-28  San Francisco

### Selection Methods

#### Selection by column

In [18]:
df = pd.read_csv("sample-employees.csv")

# print(df["name"].to_string())

print(df[["name","department"]].to_string())

                name   department
0        Marcus Chen  Engineering
1       Priya Sharma  Engineering
2          David Kim  Engineering
3      Rachel Torres  Engineering
4       James Okafor  Engineering
5          Lena Vogt  Engineering
6         Amir Patel  Engineering
7     Sofia Lindberg       Design
8      Carlos Rivera       Design
9      Hannah Becker       Design
10       Yuki Tanaka       Design
11     Olivia Martin    Marketing
12      Ethan Brooks    Marketing
13     Nina Kowalski    Marketing
14      Daniel Ochoa    Marketing
15     Samira Hassan    Marketing
16  Tyler Washington        Sales
17     Jessica Huang        Sales
18      Ryan O'Brien        Sales
19  Fatima Al-Rashid        Sales
20      Kevin Dupont        Sales
21     Megan Stewart        Sales
22        Laura Chen           HR
23    Brian Nakamura           HR
24      Chloe Dubois           HR
25    Angela Moretti           HR
26   Isaac Fernandez  Engineering
27    Sarah Mitchell       Design
28        Omar Farah  Engineering
29      Natalie Park    Marketing

#### Selection By Rows

In [ ]:
print(df.loc[2])

name                      David Kim
email         david.kim@example.com
department              Engineering
role              Software Engineer
salary                       125000
start_date               2021-01-10
office                     New York
Name: 2, dtype: object

In [24]:
df = pd.read_csv("sample-employees.csv", index_col="name")

In [25]:
print(df.loc["Marcus Chen"])

email          marcus.chen@example.com
department                 Engineering
role          Senior Software Engineer
salary                          155000
start_date                  2019-03-15
office                   San Francisco
Name: Marcus Chen, dtype: object

In [33]:
print(df.loc["Marcus Chen":"Yuki Tanaka",["email","department","salary"]])

                                     email   department  salary
name
Marcus Chen        marcus.chen@example.com  Engineering  155000
Priya Sharma      priya.sharma@example.com  Engineering  178000
David Kim            david.kim@example.com  Engineering  125000
Rachel Torres    rachel.torres@example.com  Engineering  168000
James Okafor      james.okafor@example.com  Engineering   92000
Lena Vogt            lena.vogt@example.com  Engineering  140000
Amir Patel          amir.patel@example.com  Engineering  132000
Sofia Lindberg  sofia.lindberg@example.com       Design  145000
Carlos Rivera    carlos.rivera@example.com       Design  112000
Hannah Becker    hannah.becker@example.com       Design  105000
Yuki Tanaka        yuki.tanaka@example.com       Design  118000

In [ ]:
print(df.iloc[0:11, 0:2]) # Column argument

                                     email   department
name
Marcus Chen        marcus.chen@example.com  Engineering
Priya Sharma      priya.sharma@example.com  Engineering
David Kim            david.kim@example.com  Engineering
Rachel Torres    rachel.torres@example.com  Engineering
James Okafor      james.okafor@example.com  Engineering
Lena Vogt            lena.vogt@example.com  Engineering
Amir Patel          amir.patel@example.com  Engineering
Sofia Lindberg  sofia.lindberg@example.com       Design
Carlos Rivera    carlos.rivera@example.com       Design
Hannah Becker    hannah.becker@example.com       Design
Yuki Tanaka        yuki.tanaka@example.com       Design

#### Filtering

In [5]:
print(df.to_string())

                name                         email   department                      role  salary  start_date         office
0        Marcus Chen       marcus.chen@example.com  Engineering  Senior Software Engineer  155000  2019-03-15  San Francisco
1       Priya Sharma      priya.sharma@example.com  Engineering            Staff Engineer  178000  2019-06-01  San Francisco
2          David Kim         david.kim@example.com  Engineering         Software Engineer  125000  2021-01-10       New York
3      Rachel Torres     rachel.torres@example.com  Engineering       Engineering Manager  168000  2020-02-20  San Francisco
4       James Okafor      james.okafor@example.com  Engineering          Junior Developer   92000  2024-06-15         Austin
5          Lena Vogt         lena.vogt@example.com  Engineering           DevOps Engineer  140000  2022-04-01       New York
6         Amir Patel        amir.patel@example.com  Engineering          Backend Engineer  132000  2023-01-09         London
7     Sofia Lindberg    sofia.lindberg@example.com       Design             Lead Designer  145000  2019-09-12       New York
8      Carlos Rivera     carlos.rivera@example.com       Design               UX Designer  112000  2021-07-20  San Francisco
9      Hannah Becker     hannah.becker@example.com       Design               UI Designer  105000  2022-11-01         London
10       Yuki Tanaka       yuki.tanaka@example.com       Design          Product Designer  118000  2023-03-14  San Francisco
11     Olivia Martin     olivia.martin@example.com    Marketing           VP of Marketing  165000  2019-04-22       New York
12      Ethan Brooks      ethan.brooks@example.com    Marketing        Content Strategist   95000  2021-10-05         Austin
13     Nina Kowalski     nina.kowalski@example.com    Marketing            SEO Specialist   88000  2022-08-15       New York
14      Daniel Ochoa      daniel.ochoa@example.com    Marketing         Marketing Analyst   91000  2023-05-20         Austin
15     Samira Hassan     samira.hassan@example.com    Marketing      Social Media Manager   82000  2024-01-08         London
16  Tyler Washington  tyler.washington@example.com        Sales            Sales Director  158000  2019-11-30       New York
17     Jessica Huang     jessica.huang@example.com        Sales         Account Executive  110000  2020-06-14  San Francisco
18      Ryan O'Brien       ryan.obrien@example.com        Sales         Account Executive  105000  2021-03-22         London
19  Fatima Al-Rashid   fatima.alrashid@example.com        Sales     Sales Development Rep   72000  2023-09-01         Austin
20      Kevin Dupont      kevin.dupont@example.com        Sales        Solutions Engineer  135000  2022-01-17  San Francisco
21     Megan Stewart     megan.stewart@example.com        Sales           Account Manager   98000  2024-03-11       New York
22        Laura Chen        laura.chen@example.com           HR               HR Director  148000  2019-08-05       New York
23    Brian Nakamura    brian.nakamura@example.com           HR       HR Business Partner  105000  2020-12-01  San Francisco
24      Chloe Dubois      chloe.dubois@example.com           HR                 Recruiter   78000  2022-05-23         London
25    Angela Moretti    angela.moretti@example.com           HR         People Operations   85000  2023-07-10         Austin
26   Isaac Fernandez   isaac.fernandez@example.com  Engineering         Frontend Engineer  128000  2022-09-19       New York
27    Sarah Mitchell    sarah.mitchell@example.com       Design       Design Systems Lead  138000  2020-04-06  San Francisco
28        Omar Farah        omar.farah@example.com  Engineering               QA Engineer   95000  2024-02-12         London
29      Natalie Park      natalie.park@example.com    Marketing            Growth Manager  108000  2021-11-28  San Francisco

In [4]:
df = pd.read_csv("sample-employees.csv")

highest_earner = df[df["salary"] > 150000]

print(highest_earner.to_string())

                name                         email   department                      role  salary  start_date         office
0        Marcus Chen       marcus.chen@example.com  Engineering  Senior Software Engineer  155000  2019-03-15  San Francisco
1       Priya Sharma      priya.sharma@example.com  Engineering            Staff Engineer  178000  2019-06-01  San Francisco
3      Rachel Torres     rachel.torres@example.com  Engineering       Engineering Manager  168000  2020-02-20  San Francisco
11     Olivia Martin     olivia.martin@example.com    Marketing           VP of Marketing  165000  2019-04-22       New York
16  Tyler Washington  tyler.washington@example.com        Sales            Sales Director  158000  2019-11-30       New York

In [7]:
desgin_team = df[df["department"]=="Design"]

print(desgin_team.to_string())

              name                       email department                 role  salary  start_date         office
7   Sofia Lindberg  sofia.lindberg@example.com     Design        Lead Designer  145000  2019-09-12       New York
8    Carlos Rivera   carlos.rivera@example.com     Design          UX Designer  112000  2021-07-20  San Francisco
9    Hannah Becker   hannah.becker@example.com     Design          UI Designer  105000  2022-11-01         London
10     Yuki Tanaka     yuki.tanaka@example.com     Design     Product Designer  118000  2023-03-14  San Francisco
27  Sarah Mitchell  sarah.mitchell@example.com     Design  Design Systems Lead  138000  2020-04-06  San Francisco

#### Agregate Function - `groupby()`

In [9]:
df = pd.read_csv("sample-employees.csv")

print(df.to_string())

                name                         email   department                      role  salary  start_date         office
0        Marcus Chen       marcus.chen@example.com  Engineering  Senior Software Engineer  155000  2019-03-15  San Francisco
1       Priya Sharma      priya.sharma@example.com  Engineering            Staff Engineer  178000  2019-06-01  San Francisco
2          David Kim         david.kim@example.com  Engineering         Software Engineer  125000  2021-01-10       New York
3      Rachel Torres     rachel.torres@example.com  Engineering       Engineering Manager  168000  2020-02-20  San Francisco
4       James Okafor      james.okafor@example.com  Engineering          Junior Developer   92000  2024-06-15         Austin
5          Lena Vogt         lena.vogt@example.com  Engineering           DevOps Engineer  140000  2022-04-01       New York
6         Amir Patel        amir.patel@example.com  Engineering          Backend Engineer  132000  2023-01-09         London
7     Sofia Lindberg    sofia.lindberg@example.com       Design             Lead Designer  145000  2019-09-12       New York
8      Carlos Rivera     carlos.rivera@example.com       Design               UX Designer  112000  2021-07-20  San Francisco
9      Hannah Becker     hannah.becker@example.com       Design               UI Designer  105000  2022-11-01         London
10       Yuki Tanaka       yuki.tanaka@example.com       Design          Product Designer  118000  2023-03-14  San Francisco
11     Olivia Martin     olivia.martin@example.com    Marketing           VP of Marketing  165000  2019-04-22       New York
12      Ethan Brooks      ethan.brooks@example.com    Marketing        Content Strategist   95000  2021-10-05         Austin
13     Nina Kowalski     nina.kowalski@example.com    Marketing            SEO Specialist   88000  2022-08-15       New York
14      Daniel Ochoa      daniel.ochoa@example.com    Marketing         Marketing Analyst   91000  2023-05-20         Austin
15     Samira Hassan     samira.hassan@example.com    Marketing      Social Media Manager   82000  2024-01-08         London
16  Tyler Washington  tyler.washington@example.com        Sales            Sales Director  158000  2019-11-30       New York
17     Jessica Huang     jessica.huang@example.com        Sales         Account Executive  110000  2020-06-14  San Francisco
18      Ryan O'Brien       ryan.obrien@example.com        Sales         Account Executive  105000  2021-03-22         London
19  Fatima Al-Rashid   fatima.alrashid@example.com        Sales     Sales Development Rep   72000  2023-09-01         Austin
20      Kevin Dupont      kevin.dupont@example.com        Sales        Solutions Engineer  135000  2022-01-17  San Francisco
21     Megan Stewart     megan.stewart@example.com        Sales           Account Manager   98000  2024-03-11       New York
22        Laura Chen        laura.chen@example.com           HR               HR Director  148000  2019-08-05       New York
23    Brian Nakamura    brian.nakamura@example.com           HR       HR Business Partner  105000  2020-12-01  San Francisco
24      Chloe Dubois      chloe.dubois@example.com           HR                 Recruiter   78000  2022-05-23         London
25    Angela Moretti    angela.moretti@example.com           HR         People Operations   85000  2023-07-10         Austin
26   Isaac Fernandez   isaac.fernandez@example.com  Engineering         Frontend Engineer  128000  2022-09-19       New York
27    Sarah Mitchell    sarah.mitchell@example.com       Design       Design Systems Lead  138000  2020-04-06  San Francisco
28        Omar Farah        omar.farah@example.com  Engineering               QA Engineer   95000  2024-02-12         London
29      Natalie Park      natalie.park@example.com    Marketing            Growth Manager  108000  2021-11-28  San Francisco

In [10]:
print(df.mean(numeric_only=True))

salary    118466.666667
dtype: float64

In [11]:
print(df.sum(numeric_only=True))

salary    3554000
dtype: int64

In [12]:
print(df.min(numeric_only=True))

salary    72000
dtype: int64

In [13]:
print(df.max(numeric_only=True))

salary    178000
dtype: int64

In [ ]:
print(df.count())

name          30
email         30
department    30
role          30
salary        30
start_date    30
office        30
dtype: int64

In [17]:
group = df.groupby("department")

print(group["salary"].max())

department
Design         145000
Engineering    178000
HR             148000
Marketing      165000
Sales          158000
Name: salary, dtype: int64