## Pandas

### Why `pandas`?

Data is increasingly central to decision making across industries. While tools like Excel are useful for simple analysis, they fall short when you need to automate workflows, collaborate on a shared codebase, or scale to larger datasets.

`pandas` addresses these limitations by providing a powerful, programmable interface for data analysis in Python: 

* Automate analyses so they re-run on new data each day
* Build a scalable, version-controlled codebase with colleagues
* Perform robust analyses that feed directly into business decisions
* Prepare and transform data for machine learning pipelines

`pandas` is one of the core libraries used by data analysts and data scientists in Python.

In [1]:
import pandas as pd

### Creating a DataFrame

`pandas` is a library that provides data types and functions for rigorous, programmatic data analysis. The core `pandas` data type is the DataFrame.

A `DataFrame` is a two-dimensional table of named rows and columns, similiar to a SQL table. The DataFrame class accepts a data attribute that defines the content of the table at instantiation

To create a DataFrame, you can pass a list of lists where each inner list represents a row of data

|Name | Age | Job
|---|---|---|
|John | 30 | Journalist |
|Mary | 30 | Programmer |
|Abe | 40 | Chef|

In [2]:
data = [["John",30,"Journalist"],["Mary",30,"Programmer"],["Abe",40,"Chef"]]

df = pd.DataFrame(data=data)
df

      0   1           2
0  John  30  Journalist
1  Mary  30  Programmer
2   Abe  40        Chef

### Adding Column Names

The column headers `0, 1, 2` shown above are default integer values assigned when no columns names are provided. To assign meaningful column names, pass a list of strings to the columns attribute of `pd.Dataframe()`.

In [3]:
cols = ["Name","Age","Job"]

df = pd.DataFrame(data=data, columns=cols)
df

   Name  Age         Job
0  John   30  Journalist
1  Mary   30  Programmer
2   Abe   40        Chef

In [4]:
df.dtypes

Name      str
Age     int64
Job       str
dtype: object

### Creating DataFrame from a NumPy ndarray

You can also create a Dataframe from a NumPy array. This is useful when your data is already in array form, such as after numerical computations or loading from external sources. Simply pass the NumPy array as the data argument and specify column names with the columns parameter.

In [5]:
import numpy as np

np_array = np.array([
    ["John",30,"Journalist"],
    ["Mary",30,"Programmer"],
    ["Abe",40,"Chef"]
    ])

df2 = pd.DataFrame(data=np_array, columns=cols)
df2

   Name Age         Job
0  John  30  Journalist
1  Mary  30  Programmer
2   Abe  40        Chef

In [6]:
df2.dtypes

Name    str
Age     str
Job     str
dtype: object

<div class="alert alert-info">
Note:
When creating a DataFrame from a NumPy array containing mixed types, NumPy assigns the 'object' dtype to all elements, so pandas infers all columns as object type
</div>

### The Series Datatype

The other primary data type in `pandas` is the Series. A Series represents a single column of a Dataframe.

There are two ways to select a Series from a Dataframe:
1. `df["column_name"]` -- bracket indexing (preferred)
2. `df.column_name` -- attribute reference

It is preferred to use `df["column_name"]` because the attribute reference notation does not work when column names contain spaces

In [7]:
df["Age"]

0    30
1    30
2    40
Name: Age, dtype: int64

In [8]:
df.Age

0    30
1    30
2    40
Name: Age, dtype: int64

In [9]:
df2.Age

0    30
1    30
2    40
Name: Age, dtype: str

### `dtypes` and `Series` Operations

When you display a `Series`, you will notice a `dtype` label at the bottom (e.g., `dtype: int64`). In `pandas` `dtypes` describes the type of values stored in a column.

Just as Python's built in types determine what operations are valid, the dtype of a `pandas` column determines what operations can be performed on it. For example, you can compute the average of a numeric column, but not a text column

| `pandas` dtype | Description | Python equivalent |
|---|---|---|
| `object` | Text/string data | `str` |
| `int64` | Integer values | `int` |
| `float64` | Floating-point values | `float` |
| `bool` | Boolean values | `bool` |

Operations on a Series behave similarly to operations on their Python counterpart types, but they act **element-wise** -- meaning the operation is applied to every value in the column

For example, adding two int64 Series together produces a new Series where each element is the sum of the corresponding elements

In [10]:
df["Age"] + df["Age"]

0    60
1    60
2    80
Name: Age, dtype: int64

In [11]:
df["Age"] + 3 - 1

0    32
1    32
2    42
Name: Age, dtype: int64

### Selecting a Single Value

To retrieve a single value from a Series, use integer-based notation - the same syntax used to index into a Python list. The example below retrieves the first value from the Age colum.

In [12]:
df["Age"][0]

print(df["Age"][0])

30

### Selecting Multiple Columns

In addition to selecting a single column as a Series, you can select a subset of columns and return the result as a Dataframe.

In [13]:
df[["Name","Age","Job"]]

   Name  Age         Job
0  John   30  Journalist
1  Mary   30  Programmer
2   Abe   40        Chef

### Using `iloc` for integer-based indexing

The `iloc` method allows you to select rows and columns by their integer positions.

The syntax is:
`df.iloc[row_selection, column_selection]`

In the expression df.iloc[:, [0,2]], the colon(:) before the comma means "select all rows" while [0,2] after the comma specifies the first and third columns. This is useful when you want to select columns by their order rather than by name

In [14]:
# Get the original dataframe
df

   Name  Age         Job
0  John   30  Journalist
1  Mary   30  Programmer
2   Abe   40        Chef

In [15]:
# Get the first and third column only
df.iloc[:,[0,2]]

   Name         Job
0  John  Journalist
1  Mary  Programmer
2   Abe        Chef

In [16]:
# Get the first row as a dataframe

df.iloc[:1,:]

   Name  Age         Job
0  John   30  Journalist

In [17]:
# Get the first row as a series

df.iloc[0, :]

Name          John
Age             30
Job     Journalist
Name: 0, dtype: object

<div class="alert alert-info">
<b>Note:</b>

Examples of how to use iloc to select specific rows and columns by their integer positions:

* `iloc[0, 0]` gets the first cell -- 'John'
* `iloc[:, 0]` gets the entire first column
* `iloc[0, :]` gets the entire first row

</div>

### Mutability of DataFrame Objects

When you perform an operation that modifies a DataFrame - such as dropping  a column - pandas returns a new object by default, leaving the original DataFrame unchanged. This behavior makes it safer to build complex data pipelines, since intermediate transformers do not unintentionally overwrite source data. 

The cell below drops the `Age` column and displays the result. Because the result is not assigned to a variable, it is discarded after display.

In [18]:
df.drop("Age", axis=1)

   Name         Job
0  John  Journalist
1  Mary  Programmer
2   Abe        Chef

The original DataFrame df is unchanged, as confirmed by displaying it again. To persist the result of an operation like drop(), assign the returned object to a new variable.

In [19]:
df

   Name  Age         Job
0  John   30  Journalist
1  Mary   30  Programmer
2   Abe   40        Chef

In [20]:
df_no_age = df.drop("Age", axis=1)

df_no_age

   Name         Job
0  John  Journalist
1  Mary  Programmer
2   Abe        Chef

<div class="alert alert-info">
<b>Note:</b>

The 'axis' parameter specifies whether the operation applies to rows or columns:
* axis = 1 means to operate on columns (e.g., drop a column)
* axis = 0 means to operate on rows (e.g., drop a row)
</div>

### In-Place Modification

When you want to modify a DataFrame directly - without creating a new object - you can pass `inplace=True` to the operation. In this case, no new object is returned; the change is applied to the original DataFrame

In [21]:
df.drop("Age", axis=1, inplace=True)

In [22]:
# The Age columns has been dropped from the original DataFrame

df

   Name         Job
0  John  Journalist
1  Mary  Programmer
2   Abe        Chef

### Loading Data 

`pandas` provides a function called `read_csv(path)` that accepts a file and returns a DataFrame containing the contents of that file.

In [23]:
df = pd.read_csv("employees.csv")

### Inspect the Data

To look at the first few records of the dataset, call `head()`. If you do not specify the number of rows, it defaults to 5 rows

In [24]:
df.head(3)

,name,email,department,role,salary,start_date,office
0,Marcus Chen,marcus.chen@example.com,Engineering,Senior Software Engineer,155000,2019-03-15,San Francisco
1,Priya Sharma,priya.sharma@example.com,Engineering,Staff Engineer,178000,2019-06-01,San Francisco
2,David Kim,david.kim@example.com,Engineering,Software Engineer,125000,2021-01-10,New York

Conversely, call `tail()` to look at the last few records.

In [25]:
df.tail(3)

,name,email,department,role,salary,start_date,office
27,Sarah Mitchell,sarah.mitchell@example.com,Design,Design Systems Lead,138000,2020-04-06,San Francisco
28,Omar Farah,omar.farah@example.com,Engineering,QA Engineer,95000,2024-02-12,London
29,Natalie Park,natalie.park@example.com,Marketing,Growth Manager,108000,2021-11-28,San Francisco

### Exploring DataFrame Structure

#### List all columns with df.columns

Before working with a new dataset, it is good practice to inspect its structure. The columns attribute returns an Index containing the names of all columns in the DataFrame.

This is useful for:
* Confirming column names before referencing them.
* Identifying columns that may need renaming or type conversion
* Getting a quick inventory of available fields

In [26]:
df.columns

Index(['name', 'email', 'department', 'role', 'salary', 'start_date',
       'office'],
      dtype='str')

In [27]:
list(df.columns)

['name', 'email', 'department', 'role', 'salary', 'start_date', 'office']

In [28]:
df.dtypes

name            str
email           str
department      str
role            str
salary        int64
start_date      str
office          str
dtype: object

In [29]:
# Get the data types of multiple columns.
df[["salary","email"]].dtypes

salary    int64
email       str
dtype: object

### Working with Date Columns

When `pandas` reads a CSV file, date columns are typically loaded as plain strings. To perform any date-based operations - such as sorting by date, calculating time differences, or extracting year/month values - the column must first be converted to a proper datetime64 type.

The `pd.to_datetime()` function parses a Series of date strings into datetime objects. We use the format parameter to tell exactly how the input strings are structured.

In [30]:
df["start_date"]

0     2019-03-15
1     2019-06-01
2     2021-01-10
3     2020-02-20
4     2024-06-15
5     2022-04-01
6     2023-01-09
7     2019-09-12
8     2021-07-20
9     2022-11-01
10    2023-03-14
11    2019-04-22
12    2021-10-05
13    2022-08-15
14    2023-05-20
15    2024-01-08
16    2019-11-30
17    2020-06-14
18    2021-03-22
19    2023-09-01
20    2022-01-17
21    2024-03-11
22    2019-08-05
23    2020-12-01
24    2022-05-23
25    2023-07-10
26    2022-09-19
27    2020-04-06
28    2024-02-12
29    2021-11-28
Name: start_date, dtype: str

In [31]:
df["start_date"] = pd.to_datetime(df["start_date"])

In [32]:
df[["name","start_date"]].head(10)

             name start_date
0     Marcus Chen 2019-03-15
1    Priya Sharma 2019-06-01
2       David Kim 2021-01-10
3   Rachel Torres 2020-02-20
4    James Okafor 2024-06-15
5       Lena Vogt 2022-04-01
6      Amir Patel 2023-01-09
7  Sofia Lindberg 2019-09-12
8   Carlos Rivera 2021-07-20
9   Hannah Becker 2022-11-01

In [33]:
df[["name","start_date"]].dtypes

name                     str
start_date    datetime64[us]
dtype: object

### Reformate Dates with `strftime()`

Once a column has been converted to `datetime64`, we can reformat the date values into any string respresentation we need using `strftime()` (shor for string format time).

If we want to display dates in MM-DD-YYYY format (e.g., 07-23-2009). We achieve this with the format string `"%m-%d-%Y"`

<div class="alert alert-info">
    <b>Note:</b>

`strftime()` converts the column back to object (string) dtype. If you need to keep the column as `datetim64` for further date operations, store the formatted version in a seperate column.
</div>

In [34]:
df["start_date"] = df["start_date"].dt.strftime("%m-%d-%Y")

In [35]:
df.head(3)

,name,email,department,role,salary,start_date,office
0,Marcus Chen,marcus.chen@example.com,Engineering,Senior Software Engineer,155000,03-15-2019,San Francisco
1,Priya Sharma,priya.sharma@example.com,Engineering,Staff Engineer,178000,06-01-2019,San Francisco
2,David Kim,david.kim@example.com,Engineering,Software Engineer,125000,01-10-2021,New York

### Renaming Columns

We can rename columns of a DataFrame using `rename()`. We pass a dictionary to the columns parameter that maps old column names to new ones.

The syntax for renaming one column is:
df = df.rename(columns={"old_name": "new_name"})

The syntax for renaming more than one column is:
df.rename(columns={"old_col_a": "new_col_a", "old_col_b": "new_col_b:})

In [36]:
df = df.rename(columns={"name": "Name"})

In [37]:
df.head(3)

,Name,email,department,role,salary,start_date,office
0,Marcus Chen,marcus.chen@example.com,Engineering,Senior Software Engineer,155000,03-15-2019,San Francisco
1,Priya Sharma,priya.sharma@example.com,Engineering,Staff Engineer,178000,06-01-2019,San Francisco
2,David Kim,david.kim@example.com,Engineering,Software Engineer,125000,01-10-2021,New York

### Filtering

To select a subset of rows that meet a certain condition, use the syntax `df[bool_array]`, where `bool_array` is a series of True and False values - one per row

* Rows that evaluate to True are kept
* Rows that evaluate to False are dropped

In [38]:
df

,Name,email,department,role,salary,start_date,office
0,Marcus Chen,marcus.chen@example.com,Engineering,Senior Software Engineer,155000,03-15-2019,San Francisco
1,Priya Sharma,priya.sharma@example.com,Engineering,Staff Engineer,178000,06-01-2019,San Francisco
2,David Kim,david.kim@example.com,Engineering,Software Engineer,125000,01-10-2021,New York
3,Rachel Torres,rachel.torres@example.com,Engineering,Engineering Manager,168000,02-20-2020,San Francisco
4,James Okafor,james.okafor@example.com,Engineering,Junior Developer,92000,06-15-2024,Austin
5,Lena Vogt,lena.vogt@example.com,Engineering,DevOps Engineer,140000,04-01-2022,New York
6,Amir Patel,amir.patel@example.com,Engineering,Backend Engineer,132000,01-09-2023,London
7,Sofia Lindberg,sofia.lindberg@example.com,Design,Lead Designer,145000,09-12-2019,New York
8,Carlos Rivera,carlos.rivera@example.com,Design,UX Designer,112000,07-20-2021,San Francisco
9,Hannah Becker,hannah.becker@example.com,Design,UI Designer,105000,11-01-2022,London
10,Yuki Tanaka,yuki.tanaka@example.com,Design,Product Designer,118000,03-14-2023,San Francisco
11,Olivia Martin,olivia.martin@example.com,Marketing,VP of Marketing,165000,04-22-2019,New York
12,Ethan Brooks,ethan.brooks@example.com,Marketing,Content Strategist,95000,10-05-2021,Austin
13,Nina Kowalski,nina.kowalski@example.com,Marketing,SEO Specialist,88000,08-15-2022,New York
14,Daniel Ochoa,daniel.ochoa@example.com,Marketing,Marketing Analyst,91000,05-20-2023,Austin
15,Samira Hassan,samira.hassan@example.com,Marketing,Social Media Manager,82000,01-08-2024,London
16,Tyler Washington,tyler.washington@example.com,Sales,Sales Director,158000,11-30-2019,New York
17,Jessica Huang,jessica.huang@example.com,Sales,Account Executive,110000,06-14-2020,San Francisco
18,Ryan O'Brien,ryan.obrien@example.com,Sales,Account Executive,105000,03-22-2021,London
19,Fatima Al-Rashid,fatima.alrashid@example.com,Sales,Sales Development Rep,72000,09-01-2023,Austin
20,Kevin Dupont,kevin.dupont@example.com,Sales,Solutions Engineer,135000,01-17-2022,San Francisco
21,Megan Stewart,megan.stewart@example.com,Sales,Account Manager,98000,03-11-2024,New York
22,Laura Chen,laura.chen@example.com,HR,HR Director,148000,08-05-2019,New York
23,Brian Nakamura,brian.nakamura@example.com,HR,HR Business Partner,105000,12-01-2020,San Francisco
24,Chloe Dubois,chloe.dubois@example.com,HR,Recruiter,78000,05-23-2022,London
25,Angela Moretti,angela.moretti@example.com,HR,People Operations,85000,07-10-2023,Austin
26,Isaac Fernandez,isaac.fernandez@example.com,Engineering,Frontend Engineer,128000,09-19-2022,New York
27,Sarah Mitchell,sarah.mitchell@example.com,Design,Design Systems Lead,138000,04-06-2020,San Francisco
28,Omar Farah,omar.farah@example.com,Engineering,QA Engineer,95000,02-12-2024,London
29,Natalie Park,natalie.park@example.com,Marketing,Growth Manager,108000,11-28-2021,San Francisco

In [41]:
df["department"] == "HR"

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22     True
23     True
24     True
25     True
26    False
27    False
28    False
29    False
Name: department, dtype: bool

In [48]:
filtered_df = df[(df["department"] == "Sales") & (df["office"] == "New York")]

filtered_df[["Name","department","office"]]

                Name department    office
16  Tyler Washington      Sales  New York
21     Megan Stewart      Sales  New York

### Aggregate Functions

Aggregate functions take a series of inputs and single output value.

In [57]:
print(df["salary"].mean().round())
print(df["salary"].min())
print(df["salary"].max())
print(df["salary"].sum())
print(df["salary"].count())

118467.0
72000
178000
3554000
30

### Summary with `describe()`

In [50]:
df["salary"].describe()

count        30.000000
mean     118466.666667
std       29354.824938
min       72000.000000
25%       95000.000000
50%      111000.000000
75%      139500.000000
max      178000.000000
Name: salary, dtype: float64

In [54]:
df[["salary","start_date"]].describe()

# Works with only numerical columns

              salary
count      30.000000
mean   118466.666667
std     29354.824938
min     72000.000000
25%     95000.000000
50%    111000.000000
75%    139500.000000
max    178000.000000

### Group By

The `groupby()` method splits the DataFrame into groups based on the values in one or more columns, allowing you to apply an aggregate function to each group independently

In [60]:
df.groupby(["department"])

In [64]:
grouped_df = df.groupby(["department"])[["salary"]].mean().round(2).head(10)

grouped_df

                salary
department
Design       123600.00
Engineering  134777.78
HR           104000.00
Marketing    104833.33
Sales        113000.00

In [77]:
grouped_df.columns

Index(['salary'], dtype='str')

### Sorting 
pandas provides `sort_values()` to sort rows in a DataFrame or Series

In [79]:
sorted_df = df.sort_values(["salary"])

sorted_df

,Name,email,department,role,salary,start_date,office
19,Fatima Al-Rashid,fatima.alrashid@example.com,Sales,Sales Development Rep,72000,09-01-2023,Austin
24,Chloe Dubois,chloe.dubois@example.com,HR,Recruiter,78000,05-23-2022,London
15,Samira Hassan,samira.hassan@example.com,Marketing,Social Media Manager,82000,01-08-2024,London
25,Angela Moretti,angela.moretti@example.com,HR,People Operations,85000,07-10-2023,Austin
13,Nina Kowalski,nina.kowalski@example.com,Marketing,SEO Specialist,88000,08-15-2022,New York
14,Daniel Ochoa,daniel.ochoa@example.com,Marketing,Marketing Analyst,91000,05-20-2023,Austin
4,James Okafor,james.okafor@example.com,Engineering,Junior Developer,92000,06-15-2024,Austin
12,Ethan Brooks,ethan.brooks@example.com,Marketing,Content Strategist,95000,10-05-2021,Austin
28,Omar Farah,omar.farah@example.com,Engineering,QA Engineer,95000,02-12-2024,London
21,Megan Stewart,megan.stewart@example.com,Sales,Account Manager,98000,03-11-2024,New York
23,Brian Nakamura,brian.nakamura@example.com,HR,HR Business Partner,105000,12-01-2020,San Francisco
18,Ryan O'Brien,ryan.obrien@example.com,Sales,Account Executive,105000,03-22-2021,London
9,Hannah Becker,hannah.becker@example.com,Design,UI Designer,105000,11-01-2022,London
29,Natalie Park,natalie.park@example.com,Marketing,Growth Manager,108000,11-28-2021,San Francisco
17,Jessica Huang,jessica.huang@example.com,Sales,Account Executive,110000,06-14-2020,San Francisco
8,Carlos Rivera,carlos.rivera@example.com,Design,UX Designer,112000,07-20-2021,San Francisco
10,Yuki Tanaka,yuki.tanaka@example.com,Design,Product Designer,118000,03-14-2023,San Francisco
2,David Kim,david.kim@example.com,Engineering,Software Engineer,125000,01-10-2021,New York
26,Isaac Fernandez,isaac.fernandez@example.com,Engineering,Frontend Engineer,128000,09-19-2022,New York
6,Amir Patel,amir.patel@example.com,Engineering,Backend Engineer,132000,01-09-2023,London
20,Kevin Dupont,kevin.dupont@example.com,Sales,Solutions Engineer,135000,01-17-2022,San Francisco
27,Sarah Mitchell,sarah.mitchell@example.com,Design,Design Systems Lead,138000,04-06-2020,San Francisco
5,Lena Vogt,lena.vogt@example.com,Engineering,DevOps Engineer,140000,04-01-2022,New York
7,Sofia Lindberg,sofia.lindberg@example.com,Design,Lead Designer,145000,09-12-2019,New York
22,Laura Chen,laura.chen@example.com,HR,HR Director,148000,08-05-2019,New York
0,Marcus Chen,marcus.chen@example.com,Engineering,Senior Software Engineer,155000,03-15-2019,San Francisco
16,Tyler Washington,tyler.washington@example.com,Sales,Sales Director,158000,11-30-2019,New York
11,Olivia Martin,olivia.martin@example.com,Marketing,VP of Marketing,165000,04-22-2019,New York
3,Rachel Torres,rachel.torres@example.com,Engineering,Engineering Manager,168000,02-20-2020,San Francisco
1,Priya Sharma,priya.sharma@example.com,Engineering,Staff Engineer,178000,06-01-2019,San Francisco

In [80]:
df["salary"].sort_values(ascending=False)

1     178000
3     168000
11    165000
16    158000
0     155000
22    148000
7     145000
5     140000
27    138000
20    135000
6     132000
26    128000
2     125000
10    118000
8     112000
17    110000
29    108000
9     105000
23    105000
18    105000
21     98000
12     95000
28     95000
4      92000
14     91000
13     88000
25     85000
15     82000
24     78000
19     72000
Name: salary, dtype: int64