## Pandas

### Why `pandas`?

Data is increasingly central to decision making across industries. While tools like Excel are useful for simple analysis, they fall short when you need to automate workflows, collaborate on a shared codebase, or scale to larger datasets.

`pandas` addresses these limitations by providing a powerful, programmable interface for data analysis in Python: 

* Automate analyses so they re-run on new data each day
* Build a scalable, version-controlled codebase with colleagues
* Perform robust analyses that feed directly into business decisions
* Prepare and transform data for machine learning pipelines

`pandas` is one of the core libraries used by data analysts and data scientists in Python.

In [1]:
import pandas as pd

### Creating a DataFrame

`pandas` is a library that provides data types and functions for rigorous, programmatic data analysis. The core `pandas` data type is the DataFrame.

A `DataFrame` is a two-dimensional table of named rows and columns, similiar to a SQL table. The DataFrame class accepts a data attribute that defines the content of the table at instantiation

To create a DataFrame, you can pass a list of lists where each inner list represents a row of data

|Name | Age | Job
|---|---|---|
|John | 30 | Journalist |
|Mary | 30 | Programmer |
|Abe | 40 | Chef|

In [2]:
data = [["John",30,"Journalist"],["Mary",30,"Programmer"],["Abe",40,"Chef"]]

df = pd.DataFrame(data=data)
df

      0   1           2
0  John  30  Journalist
1  Mary  30  Programmer
2   Abe  40        Chef

### Adding Column Names

The column headers `0, 1, 2` shown above are default integer values assigned when no columns names are provided. To assign meaningful column names, pass a list of strings to the columns attribute of `pd.Dataframe()`.

In [3]:
cols = ["Name","Age","Job"]

df = pd.DataFrame(data=data, columns=cols)
df

   Name  Age         Job
0  John   30  Journalist
1  Mary   30  Programmer
2   Abe   40        Chef

In [4]:
df.dtypes

Name      str
Age     int64
Job       str
dtype: object

### Creating DataFrame from a NumPy ndarray

You can also create a Dataframe from a NumPy array. This is useful when your data is already in array form, such as after numerical computations or loading from external sources. Simply pass the NumPy array as the data argument and specify column names with the columns parameter.

In [5]:
import numpy as np

np_array = np.array([
    ["John",30,"Journalist"],
    ["Mary",30,"Programmer"],
    ["Abe",40,"Chef"]
    ])

df2 = pd.DataFrame(data=np_array, columns=cols)
df2

   Name Age         Job
0  John  30  Journalist
1  Mary  30  Programmer
2   Abe  40        Chef

In [6]:
df2.dtypes

Name    str
Age     str
Job     str
dtype: object

<div class="alert alert-info">
Note:
When creating a DataFrame from a NumPy array containing mixed types, NumPy assigns the 'object' dtype to all elements, so pandas infers all columns as object type
</div>

### The Series Datatype

The other primary data type in `pandas` is the Series. A Series represents a single column of a Dataframe.

There are two ways to select a Series from a Dataframe:
1. `df["column_name"]` -- bracket indexing (preferred)
2. `df.column_name` -- attribute reference

It is preferred to use `df["column_name"]` because the attribute reference notation does not work when column names contain spaces

In [7]:
df["Age"]

0    30
1    30
2    40
Name: Age, dtype: int64

In [8]:
df.Age

0    30
1    30
2    40
Name: Age, dtype: int64

In [9]:
df2.Age

0    30
1    30
2    40
Name: Age, dtype: str

### `dtypes` and `Series` Operations

When you display a `Series`, you will notice a `dtype` label at the bottom (e.g., `dtype: int64`). In `pandas` `dtypes` describes the type of values stored in a column.

Just as Python's built in types determine what operations are valid, the dtype of a `pandas` column determines what operations can be performed on it. For example, you can compute the average of a numeric column, but not a text column

| `pandas` dtype | Description | Python equivalent |
|---|---|---|
| `object` | Text/string data | `str` |
| `int64` | Integer values | `int` |
| `float64` | Floating-point values | `float` |
| `bool` | Boolean values | `bool` |

Operations on a Series behave similarly to operations on their Python counterpart types, but they act **element-wise** -- meaning the operation is applied to every value in the column

For example, adding two int64 Series together produces a new Series where each element is the sum of the corresponding elements

In [10]:
df["Age"] + df["Age"]

0    60
1    60
2    80
Name: Age, dtype: int64

In [11]:
df["Age"] + 3 - 1

0    32
1    32
2    42
Name: Age, dtype: int64

### Selecting a Single Value

To retrieve a single value from a Series, use integer-based notation - the same syntax used to index into a Python list. The example below retrieves the first value from the Age colum.

In [12]:
df["Age"][0]

print(df["Age"][0])

30

### Selecting Multiple Columns

In addition to selecting a single column as a Series, you can select a subset of columns and return the result as a Dataframe.

In [13]:
df[["Name","Age","Job"]]

   Name  Age         Job
0  John   30  Journalist
1  Mary   30  Programmer
2   Abe   40        Chef

### Using `iloc` for integer-based indexing

The `iloc` method allows you to select rows and columns by their integer positions.

The syntax is:
`df.iloc[row_selection, column_selection]`

In the expression df.iloc[:, [0,2]], the colon(:) before the comma means "select all rows" while [0,2] after the comma specifies the first and third columns. This is useful when you want to select columns by their order rather than by name

In [14]:
# Get the original dataframe
df

   Name  Age         Job
0  John   30  Journalist
1  Mary   30  Programmer
2   Abe   40        Chef

In [15]:
# Get the first and third column only
df.iloc[:,[0,2]]

   Name         Job
0  John  Journalist
1  Mary  Programmer
2   Abe        Chef

In [16]:
# Get the first row as a dataframe

df.iloc[:1,:]

   Name  Age         Job
0  John   30  Journalist

In [17]:
# Get the first row as a series

df.iloc[0, :]

Name          John
Age             30
Job     Journalist
Name: 0, dtype: object

<div class="alert alert-info">
<b>Note:</b>

Examples of how to use iloc to select specific rows and columns by their integer positions:

* `iloc[0, 0]` gets the first cell -- 'John'
* `iloc[:, 0]` gets the entire first column


</div>